### ISSUE TITLE
File Template: Mention tooltip option

### ISSUE THREAD

**Issue by ghost** [alex1701c/KDevelopTemplates#1]
From KDevelop 5.5 (currently master) KDevelop is able to show tooltips for custom options for file templates.

Example:
options.kcfg
```xml
<?xml version="1.0" encoding="UTF-8"?>
<kcfg xmlns="http://www.kde.org/standards/kcfg/1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.kde.org/standards/kcfg/1.0
      http://www.kde.org/standards/kcfg/1.0/kcfg.xsd">
    <kcfgfile arg="true"/>
    <group name="">
        <entry name="example" type="String">
            <tooltip>Example tooltip (optional)</tooltip>
            <label>Example</label>
            <default>:-)</default>
        </entry>
    </group>
</kcfg>
```

See commit: [0df7362829436926d839b1e80efabf95dd62183b](https://invent.kde.org/kde/kdevelop/commit/0df7362829436926d839b1e80efabf95dd62183b)
See MR 66 at KDE Gitlab: https://invent.kde.org/kde/kdevelop/merge_requests/66

**Comment by alex1701c** [comment]
Thanks for the suggestion, I have implemented it in the last commit:
https://github.com/alex1701c/KDevelopTemplates/commit/d93c788773a36b03b1bf1f701e04eb9612709540#diff-da5bf732750017ca6d44fd13e3ef57fe

**Comment by ghost** [comment]
Thank you
